# -*- coding: utf-8 -*-
"""class 106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uEqZZnELk82PqEfN4mH0EPvf09e46eR_
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/whitehatjr/correlation/master/data/Ice-Cream%20vs%20Cold-Drink%20vs%20Temperature%20-%20Ice%20Cream%20Sale%20vs%20Temperature%20data.csv")
print(df)

import plotly.express as px
fig1 = px.scatter(df,x="Temperature",y = "Ice-cream Sales( ₹ )")
fig1.show()
fig2 = px.scatter(df,x="Temperature",y = "Cold drink sales( ₹ )")
fig2.show()
import numpy as np
df.corr()



import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/whitehatjr/correlation/master/data/Student%20Marks%20vs%20Days%20Present.csv")
print(df)



import plotly.express as px
fig1 = px.scatter(df,x="Roll No",y = "Marks In Percentage")
fig1.show()
fig2 = px.scatter(df,x="Roll No",y = "Days Present")
fig2.show()
import numpy as np
df.corr()



import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/whitehatjr/correlation/master/data/Size%20of%20TV%2C%09Average%20time%20spent%20watching%20TV%20in%20a%20week%20(hours).csv")
print(df)



import plotly.express as px
fig1 = px.scatter(df,x="Size of TV",y = "\tAverage time spent watching TV in a week (hours)")
fig1.show()
#fig2 = px.scatter(df,x="Roll No",y = "Days Present")
#fig2.show()
import numpy as np
df.corr()



import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/whitehatjr/correlation/master/data/cups%20of%20coffee%20vs%20hours%20of%20sleep.csv")
print(df)



import plotly.express as px
fig1 = px.scatter(df,x="week",y = "Coffee in ml")
fig1.show()
fig2 = px.scatter(df,x="week",y = "sleep in hours")
fig2.show()
import numpy as np
df.corr()